FROM mcr.microsoft.com/playwright/python:v1.50.0-noble
# python version 3.12.3
# Ubuntu 24.04.1 LTS (Noble Numbat)

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt \
    && playwright install --with-deps chromium

COPY reserver_squash.py .
COPY test.py .

CMD ["python", "/app/reserver_squash.py"]
